package modelofk;
// Generated 21:08:45, 9 de mar. de 2023 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Cicloformativo generated by hbm2java
 */
@Entity
@Table(name = "cicloformativo", catalog = "instituto")
public class Cicloformativo implements java.io.Serializable {

	private Integer idCiclo;
	private String nombreCiclo;
	private Integer horas;

	public Cicloformativo() {
	}

	public Cicloformativo(String nombreCiclo, Integer horas) {
		this.nombreCiclo = nombreCiclo;
		this.horas = horas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idCiclo", unique = true, nullable = false)
	public Integer getIdCiclo() {
		return this.idCiclo;
	}

	public void setIdCiclo(Integer idCiclo) {
		this.idCiclo = idCiclo;
	}

	@Column(name = "nombreCiclo", length = 100)
	public String getNombreCiclo() {
		return this.nombreCiclo;
	}

	public void setNombreCiclo(String nombreCiclo) {
		this.nombreCiclo = nombreCiclo;
	}

	@Column(name = "horas")
	public Integer getHoras() {
		return this.horas;
	}

	public void setHoras(Integer horas) {
		this.horas = horas;
	}

}
