package modelofk;
// Generated 21:08:45, 9 de mar. de 2023 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ComunidadAutonoma generated by hbm2java
 */
@Entity
@Table(name = "comunidadAutonoma", catalog = "instituto")
public class ComunidadAutonoma implements java.io.Serializable {

	private int idCa;
	private String nombre;
	private Set<Provincia> provincias = new HashSet<Provincia>(0);

	public ComunidadAutonoma() {
	}

	public ComunidadAutonoma(int idCa, String nombre) {
		this.idCa = idCa;
		this.nombre = nombre;
	}

	public ComunidadAutonoma(int idCa, String nombre, Set<Provincia> provincias) {
		this.idCa = idCa;
		this.nombre = nombre;
		this.provincias = provincias;
	}

	@Id

	@Column(name = "idCA", unique = true, nullable = false)
	public int getIdCa() {
		return this.idCa;
	}

	public void setIdCa(int idCa) {
		this.idCa = idCa;
	}

	@Column(name = "nombre", nullable = false, length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "comunidadAutonoma")
	public Set<Provincia> getProvincias() {
		return this.provincias;
	}

	public void setProvincias(Set<Provincia> provincias) {
		this.provincias = provincias;
	}

}
