package modelofk;
// Generated 21:08:45, 9 de mar. de 2023 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Provincia generated by hbm2java
 */
@Entity
@Table(name = "provincia", catalog = "instituto")
public class Provincia implements java.io.Serializable {

	private int idProvincia;
	private ComunidadAutonoma comunidadAutonoma;
	private String nombre;
	private Set<Direccion> direccions = new HashSet<Direccion>(0);

	public Provincia() {
	}

	public Provincia(int idProvincia, ComunidadAutonoma comunidadAutonoma, String nombre) {
		this.idProvincia = idProvincia;
		this.comunidadAutonoma = comunidadAutonoma;
		this.nombre = nombre;
	}

	public Provincia(int idProvincia, ComunidadAutonoma comunidadAutonoma, String nombre, Set<Direccion> direccions) {
		this.idProvincia = idProvincia;
		this.comunidadAutonoma = comunidadAutonoma;
		this.nombre = nombre;
		this.direccions = direccions;
	}

	@Id

	@Column(name = "idProvincia", unique = true, nullable = false)
	public int getIdProvincia() {
		return this.idProvincia;
	}

	public void setIdProvincia(int idProvincia) {
		this.idProvincia = idProvincia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idCA", nullable = false)
	public ComunidadAutonoma getComunidadAutonoma() {
		return this.comunidadAutonoma;
	}

	public void setComunidadAutonoma(ComunidadAutonoma comunidadAutonoma) {
		this.comunidadAutonoma = comunidadAutonoma;
	}

	@Column(name = "nombre", nullable = false, length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "provincia")
	public Set<Direccion> getDireccions() {
		return this.direccions;
	}

	public void setDireccions(Set<Direccion> direccions) {
		this.direccions = direccions;
	}

}
