package modelo;
// Generated 19:19:45, 28 de feb. de 2023 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.MapsId;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * ContactInfo generated by hbm2java
 */
@Entity
@Table(name = "contactInfo", catalog = "instituto", uniqueConstraints = @UniqueConstraint(columnNames = "email"))
public class ContactInfo implements java.io.Serializable {

	private int profesorId;
	private Profesor profesor;
	private String email;
	private String tlfMovil;

	public ContactInfo() {
	}

	public ContactInfo(Profesor profesor, String email) {
		this.profesor = profesor;
		this.email = email;
	}

	public ContactInfo(Profesor profesor, String email, String tlfMovil) {
		this.profesor = profesor;
		this.email = email;
		this.tlfMovil = tlfMovil;
	}

	// @GenericGenerator(name = "genr", strategy = "foreign",
	// parameters = @Parameter(name = "property", value = "profesor"))
	// @Id
//	@GeneratedValue(generator = "genr")
	@Id
	@Column(name = "profesorId", unique = true, nullable = false)
	public int getProfesorId() {
		return this.profesorId;
	}

	public void setProfesorId(int profesorId) {
		this.profesorId = profesorId;
	}

	@MapsId
	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "profesorId")
	//@PrimaryKeyJoinColumn
	public Profesor getProfesor() {
		return this.profesor;
	}

	@Override
	public String toString() {
		return "ContactInfo [profesorId=" + profesorId + ", email=" + email + ", tlfMovil=" + tlfMovil + "]";
	}

	public void setProfesor(Profesor profesor) {
		this.profesor = profesor;
	}

	@Column(name = "email", unique = true, nullable = false)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "tlf_movil", length = 15)
	public String getTlfMovil() {
		return this.tlfMovil;
	}

	public void setTlfMovil(String tlfMovil) {
		this.tlfMovil = tlfMovil;
	}

}
